//! Renders `docs/rules` from the rule catalog. Each rule document is a
//! generated header, a hand-written body, and a generated footer; the index is
//! generated whole. `zig build rule-docs` rewrites the files and a test keeps
//! them in sync.

const std = @import("std");
const catalog = @import("catalog.zig");
const types = @import("types.zig");

const Rule = types.Rule;
const Entry = catalog.Entry;

pub const directory = "docs/rules";
pub const index_name = "README.md";

pub const header_begin = "<!-- rule-docs:header (generated by `zig build rule-docs`) -->";
pub const header_end = "<!-- /rule-docs:header -->";
pub const footer_begin = "<!-- rule-docs:footer (generated by `zig build rule-docs`) -->";
pub const footer_end = "<!-- /rule-docs:footer -->";

/// Sections every hand-written body provides, in order.
pub const body_sections = [_][]const u8{ "## Why it matters", "## When it fires" };

const wrap_columns = 80;

/// The complete document: generated header, `body`, generated footer.
pub fn renderDocument(allocator: std.mem.Allocator, row: *const Entry, body: []const u8) ![]u8 {
    var text: std.ArrayList(u8) = .empty;
    errdefer text.deinit(allocator);
    try text.print(allocator, "# `{s}`\n\n{s}\n", .{ row.rule.code(), header_begin });
    try writeFacts(allocator, &text, row);
    try text.append(allocator, '\n');
    try writeWrapped(allocator, &text, row.summary, "");
    try text.print(allocator, "{s}\n\n{s}\n\n{s}\n", .{ header_end, body, footer_begin });
    try writeFooter(allocator, &text, row);
    try text.print(allocator, "{s}\n", .{footer_end});
    return text.toOwnedSlice(allocator);
}

/// The hand-written part of `document`, or null when its markers are absent
/// or out of order.
pub fn bodyOf(document: []const u8) ?[]const u8 {
    const header = std.mem.find(u8, document, header_end) orelse return null;
    const body_start = header + header_end.len;
    const footer = std.mem.find(u8, document[body_start..], footer_begin) orelse return null;
    return std.mem.trim(u8, document[body_start..][0..footer], "\n");
}

/// What `rule-docs` writes for a rule without a document; the check rejects it.
const placeholder = "Write this section before committing the rule.";
const skeleton = "## Why it matters\n\n" ++ placeholder ++ "\n\n## When it fires\n\n" ++ placeholder;

/// Names the first template section `body` lacks, if any.
pub fn missingSection(body: []const u8) ?[]const u8 {
    if (std.mem.find(u8, body, placeholder) != null) return placeholder;
    var cursor: usize = 0;
    for (body_sections) |section| {
        var line_start = cursor;
        cursor = while (line_start < body.len) {
            const line_end = std.mem.findScalarPos(u8, body, line_start, '\n') orelse body.len;
            if (std.mem.eql(u8, body[line_start..line_end], section)) break line_end;
            line_start = line_end + 1;
        } else return section;
    }
    return null;
}

fn writeFacts(allocator: std.mem.Allocator, text: *std.ArrayList(u8), row: *const Entry) !void {
    try text.print(allocator, "Tier: {s} · Profile: {s} · Default: {s} · Fixes: {s} · Options: ", .{
        @tagName(row.tier),
        if (row.profile) |profile| @tagName(profile) else "none",
        @tagName(row.defaultLevel()),
        switch (row.fixes) {
            .none => "none",
            .quick_fix => "quick fix",
            .fix_all => "fix all",
        },
    });
    const options = row.settings.options();
    if (options.len == 0) try text.appendSlice(allocator, "none");
    for (options, 0..) |option, index| {
        if (index != 0) try text.appendSlice(allocator, ", ");
        try text.print(allocator, "`{s}`", .{optionKey(option)});
    }
    try text.append(allocator, '\n');
}

fn optionKey(option: catalog.Setting) []const u8 {
    return switch (option) {
        inline else => |known| comptime catalog.Setting.key(known),
    };
}

fn writeFooter(allocator: std.mem.Allocator, text: *std.ArrayList(u8), row: *const Entry) !void {
    switch (row.example) {
        .source => |source| try text.print(allocator, "## Example\n\n```zig\n{s}\n```\n\n", .{source}),
        .none => {},
    }
    const options = row.settings.options();
    if (options.len != 0) {
        try text.print(allocator, "## Options\n\n", .{});
        try writeWrapped(allocator, text, "Set these in the rule's object in `zig-analyzer.json`, next to `level`:", "");
        try text.print(allocator, "\n```json\n{{\n  \"lints\": {{\n    \"rules\": {{\n      \"{s}\": {{\n        \"level\": \"warning\"", .{row.rule.code()});
        for (options) |option| {
            const default = try option.defaultText(allocator);
            defer allocator.free(default);
            try text.print(allocator, ",\n        \"{s}\": {s}", .{ optionKey(option), default });
        }
        try text.appendSlice(allocator, "\n      }\n    }\n  }\n}\n```\n\n");
        for (options) |option| {
            const default = try option.defaultText(allocator);
            defer allocator.free(default);
            const item = try allocator.print("- `{s}` (default `{s}`): {s}.", .{ optionKey(option), default, option.description() });
            defer allocator.free(item);
            try writeWrapped(allocator, text, item, "  ");
        }
        try text.append(allocator, '\n');
    }
    if (row.reference) |url| try text.print(allocator, "Reference: <{s}>\n\n", .{url});
    try text.print(allocator, "[Rule index]({s})\n", .{index_name});
}

/// Greedy word wrap at `wrap_columns`; every line after the first starts with
/// `indent`. Ends with a newline.
fn writeWrapped(allocator: std.mem.Allocator, text: *std.ArrayList(u8), prose: []const u8, indent: []const u8) !void {
    var line_width: usize = 0;
    var first = true;
    var words = std.mem.tokenizeScalar(u8, prose, ' ');
    while (words.next()) |word| {
        if (!first and word.len >= wrap_columns -| line_width) {
            try text.append(allocator, '\n');
            try text.appendSlice(allocator, indent);
            line_width = indent.len;
            first = true;
        }
        if (!first) {
            try text.append(allocator, ' ');
            line_width += 1;
        }
        try text.appendSlice(allocator, word);
        line_width += word.len;
        first = false;
    }
    try text.append(allocator, '\n');
}

const tier_titles = [_]struct { tier: types.Tier, title: []const u8, blurb: []const u8 }{
    .{
        .tier = .semantic,
        .title = "Semantic diagnostics",
        .blurb = "Always on at `error`. They report code that cannot mean what it says and cannot be configured.",
    },
    .{
        .tier = .correctness,
        .title = "Correctness rules",
        .blurb = "Valid code that is dangerous. They default to `warning`, except rules that need a project contract or compiler facts, which stay off until configured.",
    },
    .{
        .tier = .style,
        .title = "Style rules",
        .blurb = "Off by default. A profile, the `style` tier setting, or a per-rule setting turns them on.",
    },
};

const profile_order = [_]?types.LintProfile{ .official, .idiomatic, .strict, .modernize, .disciplined, null };

fn profileTitle(profile: ?types.LintProfile) []const u8 {
    return if (profile) |known| switch (known) {
        .none => unreachable,
        .official => "Profile `official`",
        .idiomatic => "Profile `idiomatic`",
        .strict => "Profile `strict`",
        .modernize => "Profile `modernize`",
        .disciplined => "Profile `disciplined`",
    } else "Explicit opt-in only";
}

pub fn renderIndex(allocator: std.mem.Allocator) ![]u8 {
    var text: std.ArrayList(u8) = .empty;
    errdefer text.deinit(allocator);
    try text.print(allocator, "# Rule reference\n\n{s}\n\n", .{"<!-- Generated by `zig build rule-docs` from src/rules/catalog.zig; do not edit. -->"});
    const introduction = try allocator.print(
        "There are {d} rules. Each has a stable kebab-case code used in configuration, diagnostics, and suppression directives, and a page explaining why it exists and when it fires. Every editor diagnostic links to its page. Tiers and profiles are described in [Linting](../linting.md).",
        .{@typeInfo(Rule).@"enum".field_names.len},
    );
    defer allocator.free(introduction);
    try writeWrapped(allocator, &text, introduction, "");
    for (tier_titles) |tier_title| {
        var tier_count: usize = 0;
        for (std.enums.values(Rule)) |rule| {
            if (rule.tier() == tier_title.tier) tier_count += 1;
        }
        try text.print(allocator, "\n## {s} ({d})\n\n", .{ tier_title.title, tier_count });
        try writeWrapped(allocator, &text, tier_title.blurb, "");
        for (profile_order) |profile| {
            var heading_written = false;
            for (std.enums.values(Rule)) |rule| {
                if (rule.tier() != tier_title.tier or rule.profile() != profile) continue;
                if (!heading_written) {
                    if (tier_title.tier == .style) {
                        try text.print(allocator, "\n### {s}\n\n", .{profileTitle(profile)});
                    } else {
                        try text.append(allocator, '\n');
                    }
                    heading_written = true;
                }
                const row = catalog.entry(rule);
                const item = try allocator.print("- [`{s}`]({s}.md) — {s}", .{ rule.code(), rule.code(), row.summary });
                defer allocator.free(item);
                try writeWrapped(allocator, &text, item, "  ");
            }
        }
    }
    return text.toOwnedSlice(allocator);
}

pub const Mode = enum { check, write };

pub const Problem = error{ DocumentOutOfDate, DocumentMissing, DocumentOrphaned, DocumentMalformed, IndexOutOfDate };

/// Compares `directory` under `root` with the generated documents, printing
/// each problem; in `write` mode it rewrites stale documents instead. A
/// missing document is created from a skeleton whose placeholder body still
/// fails the check until someone writes it.
pub fn sync(io: std.Io, allocator: std.mem.Allocator, root: std.Io.Dir, mode: Mode) !void {
    var rules_dir = try root.openDir(io, directory, .{ .iterate = true });
    defer rules_dir.close(io);
    var failed = false;

    const index = try renderIndex(allocator);
    defer allocator.free(index);
    failed = try reconcile(io, allocator, rules_dir, index_name, index, mode, error.IndexOutOfDate) or failed;

    for (std.enums.values(Rule)) |rule| {
        var name_buffer: [128]u8 = undefined;
        const name = try std.mem.print(&name_buffer, "{s}.md", .{rule.code()});
        const existing = rules_dir.readFileAlloc(io, name, allocator, .limited(1 << 20)) catch |err| switch (err) {
            error.FileNotFound => {
                std.log.err("rule document {s}/{s} is missing\n", .{ directory, name });
                if (mode == .write) {
                    const created = try renderDocument(allocator, catalog.entry(rule), skeleton);
                    defer allocator.free(created);
                    try rules_dir.writeFile(io, .{ .sub_path = name, .data = created });
                }
                failed = true;
                continue;
            },
            else => |other| return other,
        };
        defer allocator.free(existing);
        const body = bodyOf(existing) orelse {
            std.log.err("{s}/{s} lacks the generated header and footer markers\n", .{ directory, name });
            failed = true;
            continue;
        };
        if (missingSection(body)) |section| {
            std.log.err("{s}/{s} lacks the section '{s}'\n", .{ directory, name, section });
            failed = true;
            continue;
        }
        const expected = try renderDocument(allocator, catalog.entry(rule), body);
        defer allocator.free(expected);
        failed = try reconcile(io, allocator, rules_dir, name, expected, mode, error.DocumentOutOfDate) or failed;
    }

    var entries = rules_dir.iterate();
    while (try entries.next(io)) |entry| {
        if (entry.kind != .file or std.mem.eql(u8, entry.name, index_name)) continue;
        const code = std.mem.cutSuffix(u8, entry.name, ".md") orelse entry.name;
        const known = for (std.enums.values(Rule)) |rule| {
            if (std.mem.eql(u8, rule.code(), code) and code.len != entry.name.len) break true;
        } else false;
        if (!known) {
            std.log.err("{s}/{s} documents no rule\n", .{ directory, entry.name });
            failed = true;
        }
    }
    if (failed) return error.RuleDocumentsOutOfSync;
}

fn reconcile(
    io: std.Io,
    allocator: std.mem.Allocator,
    dir: std.Io.Dir,
    name: []const u8,
    expected: []const u8,
    mode: Mode,
    stale: Problem,
) !bool {
    const current = dir.readFileAlloc(io, name, allocator, .limited(1 << 20)) catch |err| switch (err) {
        error.FileNotFound => null,
        else => |other| return other,
    };
    defer if (current) |bytes| allocator.free(bytes);
    if (current) |bytes| if (std.mem.eql(u8, bytes, expected)) return false;
    switch (mode) {
        .check => {
            std.log.err("{s}/{s} differs from generated output ({t}); run `zig build rule-docs`\n", .{ directory, name, stale });
            return true;
        },
        .write => {
            try dir.writeFile(io, .{ .sub_path = name, .data = expected });
            return false;
        },
    }
}

test "wrapped prose stays within the column limit" {
    var text: std.ArrayList(u8) = .empty;
    defer text.deinit(std.testing.allocator);
    try writeWrapped(
        std.testing.allocator,
        &text,
        "Reports a very long sentence about a rule that needs more than one line of eighty columns to say anything useful at all.",
        "  ",
    );
    var lines = std.mem.splitScalar(u8, std.mem.trimEnd(u8, text.items, "\n"), '\n');
    while (lines.next()) |line| try std.testing.expect(line.len <= wrap_columns);
}

test "body extraction and section checks" {
    const row = catalog.entry(.self_assignment);
    const body = "## Why it matters\n\nBecause.\n\n## When it fires\n\nOften.";
    const document = try renderDocument(std.testing.allocator, row, body);
    defer std.testing.allocator.free(document);
    try std.testing.expectEqualStrings(body, bodyOf(document).?);
    try std.testing.expect(missingSection(body) == null);
    try std.testing.expectEqualStrings("## When it fires", missingSection("## Why it matters\n\nBecause.").?);
    try std.testing.expect(bodyOf("# `x`\n") == null);
}
