const std = @import("std");

pub const Level = enum {
    off,
    hint,
    information,
    warning,
    @"error",
};

pub const Rule = enum {
    unresolved_call,
    missing_switch_prong,
    missing_struct_field,
    never_mutated_var,
    unreleased_allocation,
    defer_cleanup_in_loop,
    error_value_comparison,
    discarded_error,
    redundant_bool_comparison,
    redundant_boolean_if,
    non_exhaustive_switch_else,
    non_idiomatic_name,
    unsorted_imports,
    needless_cast,
    needless_else_after_terminator,
    needless_empty_else,
    mixed_bitwise_arithmetic,
    unused_private_declaration,
    cleanup_after_fallible_operation,
    mismatched_allocation_release,
    double_release,
    use_after_release,
    overwritten_owning_value,
    unsafe_catch_unreachable,
    lost_error_context,
    missing_resource_cleanup,
    undefined_value_escape,
    unknown_comptime_member,
    constant_comptime_condition,
    vague_type_name,
    redundant_qualified_name,
    underscore_private_name,
    non_idiomatic_file_name,
    doc_comment_style,
    public_declaration_docs,
    prefer_optional_capture,
    prefer_try,
    prefer_testing_expect_equal,
    mutable_pointer_parameter,
    redundant_comptime,
    redundant_inline,
    needless_defer_block,
    non_exhaustive_error_switch,
    duplicate_import,
    unused_import,
    redundant_import_path,
    redundant_type_qualification,
    prefer_anonymous_initializer,
    returning_local_slice,
    unsafe_orelse_unreachable,
    redundant_optional_unwrap,
    prefer_testing_expect_equal_strings,
    invalidated_container_view,
    returning_deinitialized_view,
    returning_arena_allocation,
    invalidated_element_pointer,
    defer_uses_reassigned_binding,
    error_collapsed_to_absence,
    allocation_size_overflow,
    resource_cleanup_on_error_only,
    iterator_invalidated_during_loop,
    prefer_testing_expect_equal_slices,
    prefer_testing_expect_error,
    prefer_testing_expect_approx,
    prefer_optional_presence_test,
    redundant_error_capture,
    needless_switch_else_capture,
    prefer_sentinel_termination,
    duplicate_c_import,
    unreferenced_test_file,
    conflicting_build_options,
    duplicate_module_import,
    returning_released_value,
    inclusive_index_bound,
    unsigned_reverse_loop,

    pub fn code(rule: Rule) []const u8 {
        return switch (rule) {
            .unresolved_call => "unresolved-call",
            .missing_switch_prong => "missing-switch-prong",
            .missing_struct_field => "missing-struct-field",
            .never_mutated_var => "never-mutated-var",
            .unreleased_allocation => "unreleased-allocation",
            .defer_cleanup_in_loop => "defer-cleanup-in-loop",
            .error_value_comparison => "error-value-comparison",
            .discarded_error => "discarded-error",
            .redundant_bool_comparison => "redundant-bool-comparison",
            .redundant_boolean_if => "redundant-boolean-if",
            .non_exhaustive_switch_else => "non-exhaustive-switch-else",
            .non_idiomatic_name => "non-idiomatic-name",
            .unsorted_imports => "unsorted-imports",
            .needless_cast => "needless-cast",
            .needless_else_after_terminator => "needless-else-after-terminator",
            .needless_empty_else => "needless-empty-else",
            .mixed_bitwise_arithmetic => "mixed-bitwise-arithmetic",
            .unused_private_declaration => "unused-private-declaration",
            .cleanup_after_fallible_operation => "cleanup-after-fallible-operation",
            .mismatched_allocation_release => "mismatched-allocation-release",
            .double_release => "double-release",
            .use_after_release => "use-after-release",
            .overwritten_owning_value => "overwritten-owning-value",
            .unsafe_catch_unreachable => "unsafe-catch-unreachable",
            .lost_error_context => "lost-error-context",
            .missing_resource_cleanup => "missing-resource-cleanup",
            .undefined_value_escape => "undefined-value-escape",
            .unknown_comptime_member => "unknown-comptime-member",
            .constant_comptime_condition => "constant-comptime-condition",
            .vague_type_name => "vague-type-name",
            .redundant_qualified_name => "redundant-qualified-name",
            .underscore_private_name => "underscore-private-name",
            .non_idiomatic_file_name => "non-idiomatic-file-name",
            .doc_comment_style => "doc-comment-style",
            .public_declaration_docs => "public-declaration-docs",
            .prefer_optional_capture => "prefer-optional-capture",
            .prefer_try => "prefer-try",
            .prefer_testing_expect_equal => "prefer-testing-expect-equal",
            .mutable_pointer_parameter => "mutable-pointer-parameter",
            .redundant_comptime => "redundant-comptime",
            .redundant_inline => "redundant-inline",
            .needless_defer_block => "needless-defer-block",
            .non_exhaustive_error_switch => "non-exhaustive-error-switch",
            .duplicate_import => "duplicate-import",
            .unused_import => "unused-import",
            .redundant_import_path => "redundant-import-path",
            .redundant_type_qualification => "redundant-type-qualification",
            .prefer_anonymous_initializer => "prefer-anonymous-initializer",
            .returning_local_slice => "returning-local-slice",
            .unsafe_orelse_unreachable => "unsafe-orelse-unreachable",
            .redundant_optional_unwrap => "redundant-optional-unwrap",
            .prefer_testing_expect_equal_strings => "prefer-testing-expect-equal-strings",
            .invalidated_container_view => "invalidated-container-view",
            .returning_deinitialized_view => "returning-deinitialized-view",
            .returning_arena_allocation => "returning-arena-allocation",
            .invalidated_element_pointer => "invalidated-element-pointer",
            .defer_uses_reassigned_binding => "defer-uses-reassigned-binding",
            .error_collapsed_to_absence => "error-collapsed-to-absence",
            .allocation_size_overflow => "allocation-size-overflow",
            .resource_cleanup_on_error_only => "resource-cleanup-on-error-only",
            .iterator_invalidated_during_loop => "iterator-invalidated-during-loop",
            .prefer_testing_expect_equal_slices => "prefer-testing-expect-equal-slices",
            .prefer_testing_expect_error => "prefer-testing-expect-error",
            .prefer_testing_expect_approx => "prefer-testing-expect-approx",
            .prefer_optional_presence_test => "prefer-optional-presence-test",
            .redundant_error_capture => "redundant-error-capture",
            .needless_switch_else_capture => "needless-switch-else-capture",
            .prefer_sentinel_termination => "prefer-sentinel-termination",
            .duplicate_c_import => "duplicate-c-import",
            .unreferenced_test_file => "unreferenced-test-file",
            .conflicting_build_options => "conflicting-build-options",
            .duplicate_module_import => "duplicate-module-import",
            .returning_released_value => "returning-released-value",
            .inclusive_index_bound => "inclusive-index-bound",
            .unsigned_reverse_loop => "unsigned-reverse-loop",
        };
    }

    pub fn tier(rule: Rule) Tier {
        return switch (rule) {
            .unresolved_call, .missing_switch_prong, .missing_struct_field, .never_mutated_var => .semantic,
            .unreleased_allocation,
            .defer_cleanup_in_loop,
            .error_value_comparison,
            .cleanup_after_fallible_operation,
            .mismatched_allocation_release,
            .double_release,
            .use_after_release,
            .overwritten_owning_value,
            .missing_resource_cleanup,
            .undefined_value_escape,
            .returning_local_slice,
            .invalidated_container_view,
            .returning_deinitialized_view,
            .returning_arena_allocation,
            .invalidated_element_pointer,
            .defer_uses_reassigned_binding,
            .error_collapsed_to_absence,
            .allocation_size_overflow,
            .resource_cleanup_on_error_only,
            .iterator_invalidated_during_loop,
            .duplicate_module_import,
            .returning_released_value,
            .unsigned_reverse_loop,
            => .correctness,
            else => .style,
        };
    }

    pub fn profile(rule: Rule) ?LintProfile {
        return switch (rule) {
            .non_idiomatic_name,
            .vague_type_name,
            .redundant_qualified_name,
            .underscore_private_name,
            .non_idiomatic_file_name,
            .doc_comment_style,
            => .official,
            .discarded_error,
            .redundant_bool_comparison,
            .redundant_boolean_if,
            .non_exhaustive_switch_else,
            .unsorted_imports,
            .needless_cast,
            .needless_else_after_terminator,
            .needless_empty_else,
            .mixed_bitwise_arithmetic,
            .unsafe_catch_unreachable,
            .lost_error_context,
            .unknown_comptime_member,
            .constant_comptime_condition,
            .prefer_optional_capture,
            .prefer_try,
            .prefer_testing_expect_equal,
            .mutable_pointer_parameter,
            .redundant_comptime,
            .redundant_inline,
            .needless_defer_block,
            .non_exhaustive_error_switch,
            .duplicate_import,
            .unused_import,
            .redundant_import_path,
            .redundant_type_qualification,
            .prefer_anonymous_initializer,
            .unsafe_orelse_unreachable,
            .redundant_optional_unwrap,
            .prefer_testing_expect_equal_strings,
            .prefer_testing_expect_equal_slices,
            .prefer_testing_expect_error,
            .prefer_testing_expect_approx,
            .prefer_optional_presence_test,
            .redundant_error_capture,
            .needless_switch_else_capture,
            .prefer_sentinel_termination,
            .duplicate_c_import,
            .unreferenced_test_file,
            .conflicting_build_options,
            .inclusive_index_bound,
            => .idiomatic,
            .public_declaration_docs => .strict,
            else => null,
        };
    }
};

pub const Tier = enum { semantic, correctness, style };

pub const Configuration = struct {
    levels: [std.meta.fields(Rule).len]Level,
    lint_profile: LintProfile = .none,
    format_profile: FormatProfile = .zig,
    format_organize_imports: bool = false,
    warning: ?[]const u8 = null,

    pub fn defaults() Configuration {
        var levels: [std.meta.fields(Rule).len]Level = undefined;
        for (std.enums.values(Rule)) |rule| {
            levels[@intFromEnum(rule)] = switch (rule.tier()) {
                .semantic => .@"error",
                .correctness => .warning,
                .style => .off,
            };
        }
        return .{ .levels = levels };
    }

    pub fn level(configuration: Configuration, rule: Rule) Level {
        return configuration.levels[@intFromEnum(rule)];
    }
};

pub const FormatProfile = enum { zig, analyzer };
pub const LintProfile = enum { none, official, idiomatic, strict };

pub const Edit = struct {
    span: std.zig.Token.Loc,
    replacement: []const u8,
};

pub const ActionKind = enum {
    quickfix,
    refactor_extract,
    refactor_rewrite,
    organize_imports,
    fix_all,
};

pub const Fix = struct {
    title: []const u8,
    kind: ActionKind,
    edits: []const Edit,
    preferred: bool = false,
    fix_all: bool = false,
};

pub const Finding = struct {
    rule: Rule,
    level: Level,
    span: std.zig.Token.Loc,
    message: []const u8,
    related: []const RelatedSpan = &.{},
    fixes: []const Fix = &.{},
};

pub const RelatedSpan = struct {
    span: std.zig.Token.Loc,
    message: []const u8,
};
